version: '3'
services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ${JFROG_HOME}/artifactory/var/:/var/opt/jfrog/artifactory
    restart: unless-stopped
